[v1]
"cargo-update 13.0.4 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-install-update",
    "cargo-install-update-config",
]
"git-graph 0.5.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["git-graph"]
"tree-sitter-cli 0.20.8 (registry+https://github.com/rust-lang/crates.io-index)" = ["tree-sitter"]
